[plugins.opt]
  path = \"/var/lib/rancher/k3s/agent/containerd\"

[plugins.cri]
  stream_server_address = \"127.0.0.1\"
  stream_server_port = \"10010\"
  [plugins.cri.cni]
    bin_dir = \"/var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69\"
    conf_dir = \"/var/lib/rancher/k3s/agent/etc/cni/net.d\"
    [plugins.cri.registry.mirrors]
      [plugins.cri.registry.mirrors.\"docker.io\"]
        endpoint = [\"http://$PRIVATE_REGISTRY\"]
      [plugins.cri.registry.mirrors.\"registry-1.docker.io\"]
        endpoint = [\"http://$PRIVATE_REGISTRY\"]
      [plugins.cri.registry.mirrors.\"k8s.gcr.io\"]
        endpoint = [\"http://$PRIVATE_REGISTRY\"]
      [plugins.cri.registry.mirrors.\"$PRIVATE_REGISTRY\"]
        endpoint = [\"http://$PRIVATE_REGISTRY\"]
    [plugins.cri.registry.auths]
      [plugins.cri.registry.auths.\"$PRIVATE_REGISTRY\"]
        username = \"$USERNAME\"
        password = \"$PASSWORD\"

[plugins.cri.containerd.runtimes.runc]
  runtime_type = \"io.containerd.runc.v2\"